import Loading from "@/components/loading";
import { getBooksAction } from "@/redux/action/getBooksAction";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import styles from "../styles/homePage.module.scss";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();
  const booksData = useSelector((state) => state.booksReducer);
  const [searchText, setSearchText] = useState("computer");

  useEffect(() => {
    dispatch(getBooksAction(searchText));
  }, []);

  console.log(booksData);
  return (
    <>
      <Head>
        <title>Magic Books</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {booksData.loading ? (
        <Loading />
      ) : (
        <>
          <main>
            <section className={styles.section1}>
              {booksData?.data?.items?.map((book, index) => {
                return (
                  <div key={index} className={styles.cards}>
                    <div className={styles.card}>
                      <Link href={`/${book?.id}`}>
                        <img
                          width={180}
                          height={220}
                          src={book?.volumeInfo?.imageLinks?.smallThumbnail}
                          alt="bookImage"
                        />
                      </Link>
                      <div>
                        <p>
                          {book?.volumeInfo?.description?.slice(0, 50)}{" "}
                          <span>more</span>
                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </section>
          </main>
        </>
      )}
    </>
  );
}
