import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState("salam");
  return (
    <>
      <Head>
        <title>Magic Books || Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={"/about"}>About</Link>
      </main>
    </>
  );
}
